07-10 11:53:51 jdbc[7]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-173]
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.message.DbException.get(DbException.java:137)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at com.googlecode.flyway.core.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
	at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1174)
	at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)
	at com.mavisto.examples.app.DbHelper.init(DbHelper.java:54)
	at com.mavisto.examples.app.ContactTest.init(ContactTest.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	... 48 more
07-10 11:53:51 jdbc[7]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-173]
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.message.DbException.get(DbException.java:137)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at com.googlecode.flyway.core.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
	at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1174)
	at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)
	at com.mavisto.examples.app.DbHelper.init(DbHelper.java:54)
	at com.mavisto.examples.app.ContactTest.init(ContactTest.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	... 48 more
07-10 12:10:21 jdbc[7]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-173]
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.message.DbException.get(DbException.java:137)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at com.googlecode.flyway.core.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
	at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1174)
	at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)
	at com.mavisto.examples.app.DbHelper.init(DbHelper.java:54)
	at com.mavisto.examples.app.ContactTest.init(ContactTest.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	... 48 more
07-10 12:10:21 jdbc[7]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-173]
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.message.DbException.get(DbException.java:137)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:171)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
	at org.h2.Driver.connect(Driver.java:73)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at com.googlecode.flyway.core.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
	at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1174)
	at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)
	at com.mavisto.examples.app.DbHelper.init(DbHelper.java:54)
	at com.mavisto.examples.app.ContactTest.init(ContactTest.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	... 48 more
2018-08-16 13:52:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "VALUES" not found; SQL statement:
insert into values (,'Beacon Park', 'Some Where', '01999 999999') [42102-196]
2018-08-16 13:52:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GOLFCOURSE VALUES (,[*]'Beacon Park', 'Some Where', '01999 999999') "; expected "), DEFAULT, NOT, EXISTS, INTERSECTS, SELECT, FROM, WITH"; SQL statement:
insert into golfcourse values (,'Beacon Park', 'Some Where', '01999 999999') [42001-196]
2018-08-16 13:53:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into golfcourse values ('Beacon Park', 'Some Where', '01999 999999') [21002-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:263)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:176)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
2018-08-16 13:57:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GOLFCOURSE ('name'[*], 'address', 'phone') VALUES ('Beacon Park', 'Some Where', '01999 999999') "; expected "identifier"; SQL statement:
insert into golfcourse ('name', 'address', 'phone') values ('Beacon Park', 'Some Where', '01999 999999') [42001-196]
2018-08-16 14:46:15 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM GOLFCOURSE 

INSERT INTO[*] GOLFCOURSE (NAME, ADDRESS, PHONE) VALUES ('Beacon Park', 'Some where', '01999 999 999') "; SQL statement:
SELECT * FROM GOLFCOURSE 

insert into GOLFCOURSE (name, address, phone) values ('Beacon Park', 'Some where', '01999 999 999') [42000-196]
2018-08-16 14:50:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 1, 'Yellow')
INSERT[*] INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 1, 'White')
INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 2, 'Yellow')
INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 2, 'White') "; SQL statement:
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 1, 'Yellow')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 1, 'White')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 2, 'Yellow')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 2, 'White') [42000-196]
2018-08-16 14:58:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) VALUES (1,1,1,468,4,1)
INSERT[*] INTO GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) VALUES (1,1,2,466,4,2) "; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,1,468,4,1)
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,2,466,4,2) [42000-196]
2018-08-16 14:59:29 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "FROMGOLFHOLERECORD" not found; SQL statement:
delete fromGOLFHOLERECORD [42102-196]
2018-08-16 14:59:40 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "FROMGOLFHOLERECORD" not found; SQL statement:
delete fromGOLFHOLERECORD [42102-196]
2018-08-16 14:59:56 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE *[*] FROM GOLFHOLERECORD "; expected "identifier"; SQL statement:
delete * FROM GOLFHOLERECORD [42001-196]
2018-08-16 15:22:53 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DELETE *[*] FROM GOLFHOLERECORD "; expected "identifier"; SQL statement:
delete * FROM GOLFHOLERECORD [42001-196]
2018-08-16 15:25:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 1, 'Yellow')
INSERT[*] INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 1, 'White')
INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 2, 'Yellow')
INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 2, 'White') "; SQL statement:
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 1, 'Yellow')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 1, 'White')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 2, 'Yellow')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 2, 'White') [42000-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,1,468,4,1) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,2,466,4,2) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,3,464,4,3) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,4,368,4,4) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,5,338,4,5) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,1,468,4,1) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,2,466,4,2) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,3,464,4,3) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,4,368,4,4) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,5,338,4,5) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,1,1,468,4,1) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,1,2,466,4,2) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,1,3,464,4,3) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,1,4,368,4,4) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,1,5,338,4,5) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,2,1,468,4,1) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,2,2,466,4,2) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,2,3,464,4,3) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,2,4,368,4,4) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,2,5,338,4,5) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,3,1,468,4,1) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,3,2,466,4,2) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,3,3,464,4,3) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,3,4,368,4,4) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,3,5,338,4,5) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,4,1,468,4,1) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,4,2,466,4,2) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,4,3,464,4,3) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,4,4,368,4,4) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,4,5,338,4,5) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,1,468,4,1) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,2,466,4,2) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,3,464,4,3) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,4,368,4,4) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,5,338,4,5) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,1,468,4,1) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,2,466,4,2) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,3,464,4,3) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,4,368,4,4) [42102-196]
2018-08-16 15:25:44 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFHOLERECORD" not found; SQL statement:
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,5,338,4,5) [42102-196]
2018-08-16 15:29:44 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-196]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:185)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:127)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:947)
	at org.h2.server.web.WebApp.process(WebApp.java:210)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 14 more
2018-08-16 15:29:44 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-196]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:185)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:127)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:947)
	at org.h2.server.web.WebApp.process(WebApp.java:210)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 14 more
2018-08-16 15:30:46 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 1, 'Yellow')
INSERT[*] INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 1, 'White')
INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 2, 'Yellow')
INSERT INTO GOLFCOURSEDATA (COURSEID, TEECOLOUR) VALUES ( 2, 'White') "; SQL statement:
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 1, 'Yellow')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 1, 'White')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 2, 'Yellow')
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 2, 'White') [42000-196]
2018-08-16 15:32:51 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM GOLFHOLERECORD 

INSERT INTO[*] GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) VALUES (1,1,1,468,4,1) "; SQL statement:
select * from GOLFHOLERECORD 

insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,1,468,4,1) [42000-196]
2018-08-16 15:36:02 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE GOLFHOLERECORD 




SELECT[*] * FROM GOLFHOLERECORD 
DELETE FROM GOLFHOLERECORD 


INSERT INTO GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) VALUES (1,1,1,468,4,1) "; SQL statement:
drop table GOLFHOLERECORD 




select * from GOLFHOLERECORD 
delete from GOLFHOLERECORD 


insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,1,468,4,1) [42000-196]
2018-08-16 15:53:30 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Column "GCS.COURSEID" not found; SQL statement:
select * from GOLFHOLERECORD ghr join GOLFCOURSEDATA gcd on ghr.COURSEID = gcd.COURSEID and ghr.COURSEDATAID = gcd.COURSEDATAID join GOLFCOURSE gc on gc.courseId =gcs.courseId  where gcd.teecolour = 'Yellow' and gc.name like 'Beacon%' [42122-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:130)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:131)
	at org.h2.command.dml.Select.prepare(Select.java:842)
	at org.h2.command.Parser.prepareCommand(Parser.java:263)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:176)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
2018-08-20 14:17:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "TRUNCATE GOLFHOLERECORD[*] "; expected "TABLE"; SQL statement:
truncate GOLFHOLERECORD [42001-196]
08-20 15:07:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: This method is not allowed for a prepared statement; use a regular statement instead. [90130-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.message.DbException.get(DbException.java:137)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:239)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at uk.co.mavisto.swingscorecard.app.HoleRecordHelper.getHoleRecordsForCourse(HoleRecordHelper.java:50)
	at uk.co.mavisto.swingscorecard.app.HoleRecordHelperTest.getHoleRecordsForCourse(HoleRecordHelperTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
08-20 15:10:48 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: This method is not allowed for a prepared statement; use a regular statement instead. [90130-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.message.DbException.get(DbException.java:137)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:239)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at uk.co.mavisto.swingscorecard.app.HoleRecordHelper.getHoleRecordsForCourse(HoleRecordHelper.java:50)
	at uk.co.mavisto.swingscorecard.app.HoleRecordHelperTest.getHoleRecordsForCourse(HoleRecordHelperTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
08-21 10:01:13 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "PUBLIC.GOLFCOURSE"; SQL statement:
TRUNCATE TABLE golfcourse [90106-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:36)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelperTest.init(GolfCourseHelperTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
08-21 10:03:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "PUBLIC.GOLFCOURSE"; SQL statement:
TRUNCATE TABLE golfcourse [90106-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:36)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelperTest.init(GolfCourseHelperTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
08-21 10:07:30 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "PUBLIC.GOLFCOURSE"; SQL statement:
TRUNCATE TABLE golfcourse [90106-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:36)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelperTest.init(GolfCourseHelperTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-08-21 10:07:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "PUBLIC.GOLFCOURSE"; SQL statement:
truncate table GOLFCOURSE [90106-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:35)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
08-21 10:10:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "ID" not found; SQL statement:
ALTER TABLE golfcourse ALTER COLUMN id restart with 1 [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4980)
	at org.h2.command.Parser.parseAlter(Parser.java:4386)
	at org.h2.command.Parser.parsePrepared(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelperTest.init(GolfCourseHelperTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-08-21 10:11:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "ID" not found; SQL statement:
ALTER TABLE golfcourse ALTER COLUMN id restart with 1 [42122-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:680)
	at org.h2.command.Parser.columnIfTableExists(Parser.java:5852)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5748)
	at org.h2.command.Parser.parseAlter(Parser.java:5007)
	at org.h2.command.Parser.parsePrepared(Parser.java:348)
	at org.h2.command.Parser.parse(Parser.java:321)
	at org.h2.command.Parser.parse(Parser.java:293)
	at org.h2.command.Parser.prepareCommand(Parser.java:258)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:176)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
08-21 10:26:16 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "ID" not found; SQL statement:
ALTER TABLE golfcourse ALTER COLUMN id restart with 1 [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.table.Table.getColumn(Table.java:613)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4980)
	at org.h2.command.Parser.parseAlter(Parser.java:4386)
	at org.h2.command.Parser.parsePrepared(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelperTest.init(GolfCourseHelperTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
08-21 10:27:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3047)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3133)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:655)
	at org.apache.commons.dbcp.DelegatingResultSet.getLong(DelegatingResultSet.java:278)
	at org.apache.commons.dbcp.DelegatingResultSet.getLong(DelegatingResultSet.java:278)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelper.getGolfCourses(GolfCourseHelper.java:30)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelperTest.testLoad(GolfCourseHelperTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
08-21 10:28:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3047)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3133)
	at org.h2.jdbc.JdbcResultSet.getLong(JdbcResultSet.java:655)
	at org.apache.commons.dbcp.DelegatingResultSet.getLong(DelegatingResultSet.java:278)
	at org.apache.commons.dbcp.DelegatingResultSet.getLong(DelegatingResultSet.java:278)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelper.getGolfCourses(GolfCourseHelper.java:30)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelperTest.testLoad(GolfCourseHelperTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
2018-08-21 12:20:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GOLFCOURSE ALTER COLUMN COURSEID RESTART WITH 1

INSERT[*] INTO GOLFCOURSE (NAME, ADDRESS, PHONE) VALUES ('Beacon Park', 'Some where', '01999 999 999') "; SQL statement:
ALTER TABLE golfcourse ALTER COLUMN courseId restart with 1

insert into GOLFCOURSE (name, address, phone) values ('Beacon Park', 'Some where', '01999 999 999') [42000-196]
2018-08-21 12:23:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "PUBLIC.GOLFCOURSEDATA"; SQL statement:
TRUNCATE TABLE GOLFCOURSEDATA [90106-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:35)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
2018-08-21 12:24:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "PUBLIC.GOLFCOURSEDATA"; SQL statement:
TRUNCATE TABLE GOLFCOURSEDATA [90106-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:35)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
2018-08-21 12:26:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Sequence "COURSEID" not found; SQL statement:
ALTER TABLE golfcoursedata ALTER COLUMN courseId restart with 1 [90036-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.dml.AlterSequence.setColumn(AlterSequence.java:59)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5821)
	at org.h2.command.Parser.parseAlter(Parser.java:5007)
	at org.h2.command.Parser.parsePrepared(Parser.java:348)
	at org.h2.command.Parser.parse(Parser.java:321)
	at org.h2.command.Parser.parse(Parser.java:293)
	at org.h2.command.Parser.prepareCommand(Parser.java:258)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:176)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.base/java.lang.Thread.run(Unknown Source)
2018-08-21 12:30:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GOLFCOURSEDATA ALTER COLUMN COURSEDATAID RESTART WITH 1
ALTER[*] TABLE GOLFHOLERECORD ALTER COLUMN ID RESTART WITH 1


INSERT INTO GOLFCOURSE (NAME, ADDRESS, PHONE) VALUES ('Beacon Park', 'Some where', '01999 999 999') "; SQL statement:
ALTER TABLE golfcoursedata ALTER COLUMN courseDataId restart with 1
ALTER TABLE golfholerecord ALTER COLUMN id restart with 1


insert into GOLFCOURSE (name, address, phone) values ('Beacon Park', 'Some where', '01999 999 999') [42000-196]
2018-08-21 12:30:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GOLFCOURSEDATA ALTER COLUMN COURSEDATAID RESTART WITH 1
ALTER[*] TABLE GOLFHOLERECORD ALTER COLUMN ID RESTART WITH 1 "; SQL statement:
ALTER TABLE golfcoursedata ALTER COLUMN courseDataId restart with 1
ALTER TABLE golfholerecord ALTER COLUMN id restart with 1 [42000-196]
2018-08-21 12:31:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GOLFCOURSEDATA ALTER COLUMN COURSEDATAID RESTART WITH 1
ALTER[*] TABLE GOLFHOLERECORD ALTER COLUMN ID RESTART WITH 1 "; SQL statement:
ALTER TABLE golfcoursedata ALTER COLUMN courseDataId restart with 1
ALTER TABLE golfholerecord ALTER COLUMN id restart with 1 [42000-196]
2018-08-21 12:32:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "TRUNCATE TABLE GOLFHOLERECORD
DELETE[*] FROM GOLFCOURSEDATA
DELETE FROM GOLFCOURSE"; SQL statement:
TRUNCATE TABLE GOLFHOLERECORD
DELETE FROM GOLFCOURSEDATA
DELETE FROM GOLFCOURSE [42000-196]
08-21 12:50:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "PUBLIC.GOLFCOURSE"; SQL statement:
TRUNCATE TABLE golfcourse [90106-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:36)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at uk.co.mavisto.swingscorecard.app.GolfCourseHelperTest.init(GolfCourseHelperTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
08-21 12:52:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "GOLFCOURSEDATE" not found; SQL statement:
DELETE FROM golfcoursedate [42102-173]
